// Self-host the web fonts. Fetches the Google Fonts CSS, keeps only the
// latin/cyrillic subsets we actually use, downloads each woff2 into
// assets/fonts/, and writes scripts/fonts.generated.css with local @font-face
// rules (to be pasted into css/styles.css). Run once (and again to refresh):
//   node scripts/fetch-fonts.mjs
// One-off dev utility; it hits the network, so it is not part of the CI deploy.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

// A modern desktop UA makes Google return woff2 src URLs.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Oswald:wght@500;600;700&family=Iosevka+Charon+Mono:wght@400;500;700&display=swap';
const KEEP = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);
const FONTS_DIR = 'assets/fonts';

const slug = (s) => s.toLowerCase().replace(/'/g, '').replace(/\s+/g, '-');

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Google emits `/* subset */\n@font-face { ... }` chunks; split on the comment.
const chunks = css.split('/*').slice(1);
mkdirSync(FONTS_DIR, { recursive: true });

const rules = [];
let downloaded = 0;
for (const chunk of chunks) {
  const subset = chunk.slice(0, chunk.indexOf('*/')).trim();
  if (!KEEP.has(subset)) continue;
  const body = chunk.slice(chunk.indexOf('*/') + 2);
  const family = body.match(/font-family:\s*'([^']+)'/)[1];
  const weight = body.match(/font-weight:\s*(\d+)/)[1];
  const url = body.match(/src:\s*url\(([^)]+)\)/)[1];
  const range = body.match(/unicode-range:\s*([^;]+);/)[1].trim();

  const name = `${slug(family)}-${weight}-${subset}.woff2`;
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  writeFileSync(join(FONTS_DIR, name), buf);
  downloaded += 1;

  rules.push(
    `@font-face {\n` +
    `  font-family: '${family}';\n` +
    `  font-style: normal;\n` +
    `  font-weight: ${weight};\n` +
    `  font-display: swap;\n` +
    `  src: url(../${FONTS_DIR}/${name}) format('woff2');\n` +
    `  unicode-range: ${range};\n` +
    `}`,
  );
}

const header =
  `/* Self-hosted web fonts (Oswald, Iosevka Charon Mono) — both OFL, see\n` +
  `   assets/fonts/OFL.txt. Generated by scripts/fetch-fonts.mjs from the\n` +
  `   Google Fonts latin/cyrillic subsets. Do not edit by hand — re-run the\n` +
  `   script to refresh. */\n\n`;
writeFileSync('css/fonts.css', header + rules.join('\n\n') + '\n');
console.log(`downloaded ${downloaded} woff2 into ${FONTS_DIR}/; wrote css/fonts.css`);
